-- 创建定时任务表
CREATE TABLE IF NOT EXISTS `data_service_scheduled_task` (
    `id` VARCHAR(64) NOT NULL COMMENT '任务ID',
    `name` VARCHAR(255) NOT NULL COMMENT '任务名称',
    `description` VARCHAR(1000) DEFAULT NULL COMMENT '任务描述',
    `service_id` VARCHAR(64) NOT NULL COMMENT '服务ID',
    `service_name` VARCHAR(255) DEFAULT NULL COMMENT '服务名称',
    `parameters` TEXT DEFAULT NULL COMMENT '服务参数（JSON格式）',
    `cron_expression` VARCHAR(100) NOT NULL COMMENT 'Cron表达式',
    `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    `create_time` BIGINT DEFAULT NULL COMMENT '创建时间',
    `update_time` BIGINT DEFAULT NULL COMMENT '更新时间',
    `create_user_id` BIGINT DEFAULT NULL COMMENT '创建用户ID',
    `last_execute_time` BIGINT DEFAULT NULL COMMENT '最后执行时间',
    `next_execute_time` BIGINT DEFAULT NULL COMMENT '下次执行时间',
    `execute_count` BIGINT DEFAULT 0 COMMENT '执行次数',
    `success_count` BIGINT DEFAULT 0 COMMENT '成功次数',
    `fail_count` BIGINT DEFAULT 0 COMMENT '失败次数',
    `last_execute_result` TINYINT(1) DEFAULT NULL COMMENT '最后执行结果',
    `last_execute_message` VARCHAR(1000) DEFAULT NULL COMMENT '最后执行消息',
    `last_execute_duration` BIGINT DEFAULT NULL COMMENT '最后执行耗时（毫秒）',
    `status` VARCHAR(20) DEFAULT 'WAITING' COMMENT '任务状态',
    `tags` VARCHAR(1000) DEFAULT NULL COMMENT '任务标签（JSON格式）',
    `timeout` BIGINT DEFAULT 60000 COMMENT '任务超时时间（毫秒）',
    `retry_count` INT DEFAULT 0 COMMENT '失败重试次数',
    `retry_interval` INT DEFAULT 60 COMMENT '失败重试间隔（秒）',
    `allow_concurrent` TINYINT(1) DEFAULT 0 COMMENT '是否允许并发执行',
    `send_notification` TINYINT(1) DEFAULT 0 COMMENT '是否发送通知',
    `notification_type` VARCHAR(50) DEFAULT NULL COMMENT '通知类型（如：email, sms, webhook）',
    `notification_receivers` VARCHAR(1000) DEFAULT NULL COMMENT '通知接收者（JSON格式）',
    `priority` INT DEFAULT 5 COMMENT '任务优先级',
    `group` VARCHAR(100) DEFAULT 'default' COMMENT '任务分组',
    PRIMARY KEY (`id`),
    INDEX `idx_service_id` (`service_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_group` (`group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务表';

-- 创建任务执行记录表
CREATE TABLE IF NOT EXISTS `data_service_task_execution` (
    `id` VARCHAR(64) NOT NULL COMMENT '执行ID',
    `task_id` VARCHAR(64) NOT NULL COMMENT '任务ID',
    `task_name` VARCHAR(255) DEFAULT NULL COMMENT '任务名称',
    `service_id` VARCHAR(64) NOT NULL COMMENT '服务ID',
    `service_name` VARCHAR(255) DEFAULT NULL COMMENT '服务名称',
    `parameters` TEXT DEFAULT NULL COMMENT '服务参数（JSON格式）',
    `start_time` BIGINT DEFAULT NULL COMMENT '开始时间',
    `end_time` BIGINT DEFAULT NULL COMMENT '结束时间',
    `duration` BIGINT DEFAULT NULL COMMENT '执行耗时（毫秒）',
    `status` VARCHAR(20) DEFAULT 'PENDING' COMMENT '执行状态',
    `result` TEXT DEFAULT NULL COMMENT '执行结果（JSON格式）',
    `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '错误消息',
    `executor_node` VARCHAR(100) DEFAULT NULL COMMENT '执行节点',
    `retry_count` INT DEFAULT 0 COMMENT '重试次数',
    `trigger_type` VARCHAR(20) DEFAULT 'SCHEDULED' COMMENT '触发类型',
    `trigger_id` VARCHAR(64) DEFAULT NULL COMMENT '触发者ID',
    PRIMARY KEY (`id`),
    INDEX `idx_task_id` (`task_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_start_time` (`start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务执行记录表';
