-- 数据服务表
CREATE TABLE IF NOT EXISTS DS_DATA_SERVICE (
    ID VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(50) NOT NULL,
    DATA_SOURCE_ID BIGINT,
    DATABASE_NAME VARCHAR(100),
    SCHEMA_NAME VARCHAR(100),
    TABLE_NAME VARCHAR(100),
    SCRIPT TEXT,
    LANGUAGE VARCHAR(50) NOT NULL,
    GROUP_ID VARCHAR(64),
    GMT_CREATE TIMESTAMP NOT NULL,
    GMT_MODIFIED TIMESTAMP NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    TIMEOUT BIGINT NOT NULL DEFAULT 30000,
    CACHE_TIME BIGINT NOT NULL DEFAULT 0,
    CREATE_USER_ID BIGINT,
    MODIFIED_USER_ID BIGINT,
    TAGS TEXT NOT NULL DEFAULT '[]',
    METADATA TEXT NOT NULL DEFAULT '{}'
);

-- 服务分组表
CREATE TABLE IF NOT EXISTS DS_SERVICE_GROUP (
    ID VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    PARENT_ID VARCHAR(64),
    ORDER_NUM INT NOT NULL DEFAULT 0,
    GMT_CREATE TIMESTAMP NOT NULL,
    GMT_MODIFIED TIMESTAMP NOT NULL,
    CREATE_USER_ID BIGINT,
    MODIFIED_USER_ID BIGINT,
    METADATA TEXT NOT NULL DEFAULT '{}'
);

-- 服务参数表
CREATE TABLE IF NOT EXISTS DS_SERVICE_PARAMETER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SERVICE_ID VARCHAR(64) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(500),
    DEFAULT_VALUE VARCHAR(500),
    REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
    ORDER_NUM INT NOT NULL DEFAULT 0,
    GMT_CREATE TIMESTAMP NOT NULL,
    GMT_MODIFIED TIMESTAMP NOT NULL,
    FOREIGN KEY (SERVICE_ID) REFERENCES DS_DATA_SERVICE(ID) ON DELETE CASCADE
);

-- 服务历史记录表
CREATE TABLE IF NOT EXISTS DS_SERVICE_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SERVICE_ID VARCHAR(64) NOT NULL,
    VERSION INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(50) NOT NULL,
    SCRIPT TEXT,
    LANGUAGE VARCHAR(50) NOT NULL,
    GROUP_ID VARCHAR(64),
    GMT_CREATE TIMESTAMP NOT NULL,
    CREATE_USER_ID BIGINT,
    COMMENT VARCHAR(500),
    FOREIGN KEY (SERVICE_ID) REFERENCES DS_DATA_SERVICE(ID) ON DELETE CASCADE
);

-- 服务标签表
CREATE TABLE IF NOT EXISTS DS_SERVICE_TAG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SERVICE_ID VARCHAR(64) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    GMT_CREATE TIMESTAMP NOT NULL,
    FOREIGN KEY (SERVICE_ID) REFERENCES DS_DATA_SERVICE(ID) ON DELETE CASCADE
);

-- 创建索引
CREATE INDEX IF NOT EXISTS IDX_DS_DATA_SERVICE_GROUP_ID ON DS_DATA_SERVICE(GROUP_ID);
CREATE INDEX IF NOT EXISTS IDX_DS_DATA_SERVICE_TYPE ON DS_DATA_SERVICE(TYPE);
CREATE INDEX IF NOT EXISTS IDX_DS_DATA_SERVICE_ENABLED ON DS_DATA_SERVICE(ENABLED);
CREATE INDEX IF NOT EXISTS IDX_DS_SERVICE_GROUP_PARENT_ID ON DS_SERVICE_GROUP(PARENT_ID);
CREATE INDEX IF NOT EXISTS IDX_DS_SERVICE_PARAMETER_SERVICE_ID ON DS_SERVICE_PARAMETER(SERVICE_ID);
CREATE INDEX IF NOT EXISTS IDX_DS_SERVICE_HISTORY_SERVICE_ID ON DS_SERVICE_HISTORY(SERVICE_ID);
CREATE INDEX IF NOT EXISTS IDX_DS_SERVICE_HISTORY_VERSION ON DS_SERVICE_HISTORY(SERVICE_ID, VERSION);
CREATE INDEX IF NOT EXISTS IDX_DS_SERVICE_TAG_SERVICE_ID ON DS_SERVICE_TAG(SERVICE_ID);
CREATE INDEX IF NOT EXISTS IDX_DS_SERVICE_TAG_NAME ON DS_SERVICE_TAG(NAME);
