/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-tools-common"))
    api(project(":magicdb-server-domain-api"))
    api(libs.org.springframework.boot.spring.boot.starter.web)
}

description = "magicdb-server-common-api"
