/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-start"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.com.github.jsqlparser.jsqlparser)
    testImplementation(libs.com.github.vertical.blank.sql.formatter)
}

description = "magicdb-server-test"
