/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-tools-base"))
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.commons.commons.collections4)
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.google.guava.guava)
    api(libs.com.alibaba.fastjson2.fastjson2)
    api(libs.cn.hutool.hutool.all)
    api(libs.org.hibernate.validator.hibernate.validator)
    api(libs.org.mapstruct.mapstruct)
    api(libs.org.mapstruct.mapstruct.processor)
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.zalando.logbook.spring.boot.starter)
    api(libs.com.baomidou.mybatis.plus)
    compileOnly(libs.org.springframework.spring.context.indexer)
}

description = "magicdb-server-tools-common"
