/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.baomidou.mybatis.plus)
    api(project(":magicdb-server-tools-common"))
    api(libs.com.h2database.h2)
    api(libs.com.zaxxer.hikaricp)
    api(libs.org.flywaydb.flyway.core)
    api(libs.org.flywaydb.flyway.mysql)
}

description = "magicdb-server-domain-repository"
