/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.freefair.lombok")
}

dependencies {
    api(project(":magicdb-server-tools-common"))
    api(project(":magicdb-server-domain-api"))
    api(project(":magicdb-server-common-api"))
    api(project(":magicdb-server-domain-core"))
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.spring.aspects)
    api(libs.com.unfbx.chatgpt.java)
    api(libs.com.theokanning.openai.gpt3.java.service)
    api(libs.commons.io.commons.io)
    api(libs.com.dtflys.forest.forest.spring)
    api(libs.com.dtflys.forest.forest.core)
    api(libs.com.alibaba.easyexcel)
    api(libs.com.deepoove.poi.tl)
    api(libs.com.itextpdf.itext.asian)
    api(libs.com.itextpdf.itextpdf)
    api(libs.org.apache.pdfbox.pdfbox)
    api(project(":magicdb-spi"))
    api(libs.com.auth0.java.jwt)
    api(libs.org.springframework.spring.context)
    api(libs.com.github.vertical.blank.sql.formatter)
    api(libs.org.springframework.boot.spring.boot.starter.websocket)

    // MapStruct and Lombok
    api(libs.org.mapstruct.mapstruct)

    // Lombok for Java
    compileOnly("org.projectlombok:lombok:1.18.30")

    // Annotation processors for Java
    annotationProcessor("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.5.5.Final")
}

// Configure Java annotation processor options
tasks.withType<JavaCompile>().configureEach {
    options.isIncremental = false
    options.compilerArgs.addAll(listOf(
        "-Amapstruct.defaultComponentModel=spring",
        "-Amapstruct.disableBuilders=true"
    ))
}

// Configure Lombok
lombok {
    version.set("1.18.30")
}

description = "magicdb-server-web-api"
