/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-tools-common"))
    api(libs.com.alibaba.druid)
    api(libs.com.h2database.h2)
    api(libs.org.springframework.spring.jdbc)
    api(libs.com.github.mwiede.jsch)
    api(libs.org.bouncycastle.bcprov.jdk18on)
    api(libs.com.squareup.okhttp3.okhttp)
    api(libs.com.zaxxer.hikaricp)
    api(libs.com.baomidou.mybatis.plus)
    api(libs.commons.beanutils.commons.beanutils)
    api(libs.com.github.jsqlparser.jsqlparser)
    api(libs.org.locationtech.jts.jts.core)
    api(libs.org.antlr.antlr4)
    api(libs.com.oceanbase.ob.sql.parser)
    api(libs.org.apache.tika.tika.core)
    testImplementation(libs.com.oracle.ojdbc.orai18n)
    testImplementation(libs.mysql.mysql.connector.java)
}

description = "magicdb-spi"
