/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-domain-api"))
    api(project(":magicdb-server-domain-repository"))
    api(libs.com.baomidou.mybatis.plus)
    api(project(":magicdb-server-tools-common"))
    api(libs.org.ehcache.ehcache)
    api(libs.javax.cache.cache.api)
    api(project(":magicdb-spi"))
    api(project(":magicdb-mysql"))
    api(libs.org.mapstruct.mapstruct)
    api(project(":magicdb-clickhouse"))
    api(project(":magicdb-db2"))
    api(project(":magicdb-dm"))
    api(project(":magicdb-h2"))
    api(project(":magicdb-hive"))
    api(project(":magicdb-kingbase"))
    api(project(":magicdb-mariadb"))
    api(project(":magicdb-mongodb"))
    api(project(":magicdb-oceanbase"))
    api(project(":magicdb-oracle"))
    api(project(":magicdb-postgresql"))
    api(project(":magicdb-presto"))
    api(project(":magicdb-sqlite"))
    api(project(":magicdb-sqlserver"))
    api(project(":magicdb-timeplus"))
    api(libs.commons.codec.commons.codec)
    api(libs.com.squareup.okhttp3.okhttp.x1)
    compileOnly(libs.org.mapstruct.mapstruct.processor)
}

description = "magicdb-server-domain-core"
