/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm")
    kotlin("plugin.spring")
    id("io.freefair.lombok")
}

dependencies {
    api(project(":magicdb-server-domain-api"))
    api(project(":magicdb-server-domain-repository"))
    api(libs.com.baomidou.mybatis.plus)
    api(project(":magicdb-server-tools-common"))
    api(libs.org.ehcache.ehcache)
    api(libs.javax.cache.cache.api)
    api(project(":magicdb-spi"))
    api(project(":magicdb-mysql"))
    api(libs.org.mapstruct.mapstruct)
    api(project(":magicdb-clickhouse"))
    api(project(":magicdb-db2"))
    api(project(":magicdb-dm"))
    api(project(":magicdb-h2"))
    api(project(":magicdb-hive"))
    api(project(":magicdb-kingbase"))
    api(project(":magicdb-mariadb"))
    api(project(":magicdb-mongodb"))
    api(project(":magicdb-oceanbase"))
    api(project(":magicdb-oracle"))
    api(project(":magicdb-postgresql"))
    api(project(":magicdb-presto"))
    api(project(":magicdb-sqlite"))
    api(project(":magicdb-sqlserver"))
    api(project(":magicdb-timeplus"))
    api(libs.commons.codec.commons.codec)
    api(libs.com.squareup.okhttp3.okhttp.x1)

    // Lombok for Java
    compileOnly("org.projectlombok:lombok:1.18.30")

    // Annotation processors for Java
    annotationProcessor("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.5.5.Final")
}

// Configure Java annotation processor options
tasks.withType<JavaCompile>().configureEach {
    options.isIncremental = false
    options.compilerArgs.addAll(listOf(
        "-Amapstruct.defaultComponentModel=spring",
        "-Amapstruct.disableBuilders=true"
    ))
}

description = "magicdb-server-domain-core"
