<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>ai.magicdb</groupId>
        <artifactId>magicdb-server-domain</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>magicdb-server-domain-core</artifactId>

    <dependencies>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-server-domain-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-server-domain-repository</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-server-tools-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-mysql</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- MapStruct dependencies -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok-mapstruct-binding</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-clickhouse</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-db2</artifactId>
            <version>${revision}</version>
        </dependency>


        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-dm</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-h2</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-hive</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-kingbase</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-mariadb</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-mongodb</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-oceanbase</artifactId>
            <version>${revision}</version>
        </dependency>


        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-oracle</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-postgresql</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-presto</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-sqlite</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-sqlserver</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>ai.magicdb</groupId>
            <artifactId>magicdb-timeplus</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.11</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.1</version>
        </dependency>
    </dependencies>
</project>
