/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-tools-base"))
    api(project(":magicdb-spi"))
    compileOnly(libs.org.hibernate.validator.hibernate.validator)
}

description = "magicdb-server-domain-api"
