/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":magicdb-server-tools-common"))
    api(project(":magicdb-server-domain-api"))
    api(project(":magicdb-server-common-api"))
    api(project(":magicdb-server-domain-core"))
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.commons.io.commons.io)
    api(libs.com.dtflys.forest.forest.spring)
    api(libs.com.alibaba.easyexcel)
}

description = "magicdb-server-admin-api"
