/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm")
    kotlin("plugin.spring")
    id("io.freefair.lombok")
}

dependencies {
    api(project(":magicdb-server-tools-common"))
    api(project(":magicdb-server-domain-api"))
    api(project(":magicdb-server-common-api"))
    api(project(":magicdb-server-domain-core"))
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.commons.io.commons.io)
    api(libs.com.dtflys.forest.forest.spring)
    api(libs.com.alibaba.easyexcel)

    // MapStruct and Lombok
    api(libs.org.mapstruct.mapstruct)

    // Lombok for Java
    compileOnly("org.projectlombok:lombok:1.18.30")

    // Annotation processors for Java
    annotationProcessor("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.5.5.Final")
}

// Configure Java annotation processor options
tasks.withType<JavaCompile>().configureEach {
    options.isIncremental = false
    options.compilerArgs.addAll(listOf(
        "-Amapstruct.defaultComponentModel=spring",
        "-Amapstruct.disableBuilders=true"
    ))
}

description = "magicdb-server-admin-api"
